# nixpacks.toml

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

# Si la commande ci-dessus ne suffit pas, essayez une configuration Nginx/PHP-FPM plus explicite:
# [start]
# cmd = "php-fpm -D && nginx -g 'daemon off;'"

# Si vous utilisez une configuration Nginx/PHP-FPM, vous pourriez aussi avoir besoin de:
# [build]
# phases = [
#   "composer install --no-dev --optimize-autoloader",
#   "npm ci",
#   "npm run build",
#   "php artisan migrate --force", # Si vous voulez exécuter les migrations au déploiement
#   "php artisan config:clear", # Pour s'assurer que le cache est vidé
#   "php artisan route:clear",
#   "php artisan view:clear"
# ]

# [variables]
# PHP_FPM_LISTEN = "0.0.0.0:9000" # Si vous optez pour php-fpm
